---
- name: Add an apt nginx signing key
  apt_key:
    url: "{{ nginx_key }}"
    state: present
  become: true

- name: Add apt repositories for nginx
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ nginx_repos }}"
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install required software
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
  become: true
