---
- import_tasks: install_packages.yml
  tags:
    - application
    - application:install_packages

- import_tasks: install_application.yml
  tags:
    - application
    - application:install_application

- import_tasks: start_application.yml
  tags:
    - application
    - application:start_application

- import_tasks: backup.yml
  tags:
    - application
    - application:backup
