---
- name: Add apt key for nodesource
  shell: "curl -sL {{ node_repo }} | sudo -E bash -"
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install required software
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - git
  become: true
