---
- block:
  - name: Look for the "index.js" process
    shell: "ps -ef |  grep {{ local_app_directory}}/index.js | grep -v grep"
    register: process_start_list
    changed_when: false
    ignore_errors: yes
    become: true

  - name: Start APP
    command: pm2 start index.js --name app chdir={{local_app_directory}}
    when: "process_start_list.stdout.find('index.js') == -1"
    become: true

  - name: "Waiting for port {{ local_app_port }} becomes available"
    wait_for:
      port: "{{ local_app_port }}"
      delay: 2
      timeout: 10
  rescue:
  - import_tasks: stop_application.yml

  - name: Application's starting timed out
    command: /bin/false
    when: state == 'initialization'

  - name: Restoring backups...
    command: "cp -r {{ backup_directory }}/. {{ local_app_directory }}"
    become: true

  - block:
    - name: Start APP
      command: pm2 start index.js --name app chdir={{local_app_directory}}
      become: true

    - name: "Waiting for port {{ local_app_port }} becomes available"
      wait_for:
        port: "{{ local_app_port }}"
        delay: 2
        timeout: 10
    rescue:
    - import_tasks: stop_application.yml

    - name: Application's starting timed out
      command: /bin/false
